name: open_weather_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_svg: ^1.0.3
  http: ^0.13.4
  fl_chart: ^0.55.0
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  flutter_toggle_tab: ^1.2.0
  icons_launcher: ^1.1.8
  rename: ^2.0.1
  location: ^4.4.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  connectivity_plus: ^2.3.6
  websafe_svg: ^2.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/app_icons/moon_sun_outline.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/weather_icons/
    - assets/app_icons/

fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf
      - asset: assets/fonts/Ubuntu-Italic.ttf
        style: italic
      - asset: assets/fonts/Ubuntu-Bold.ttf
        weight: 700
      - asset: assets/fonts/Ubuntu-Medium.ttf
        weight: 600
      - asset: assets/fonts/Ubuntu-Light.ttf
        weight: 300
      - asset: assets/fonts/Ubuntu-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        weight: 700
        style: italic
